# Site settings
author: Peter Stone
title: Software with Stone
header-img: img/home-bg.png
email: peter.stone.online@gmail.com
copyright_name: Peter Stone
description: > # this means to ignore newlines until "baseurl:"
  musings and explorations
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Peter-G-Stone

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
